version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      - "MINIO_ACCESS_KEY=TESTKEY"
      - "MINIO_SECRET_KEY=TESTSECRET"
    command: server /data
  minio_prep:
    image: mesosphere/aws-cli
    links:
      - "minio"
    environment:
      - "AWS_ACCESS_KEY_ID=TESTKEY"
      - "AWS_SECRET_ACCESS_KEY=TESTSECRET"
    entrypoint: ""
    command: >
      sh -c "
        aws --endpoint-url http://minio:9000 s3api create-bucket --bucket newbucket
      "
